from __future__ import annotations
from pathlib import Path
import sympy as sp

from vacuumforge import ProjectArchive, Status
from vacuumforge.governance import (
    ClaimRecord, ClaimTier, GovernanceStatus, ObligationStatus,
    ProofObligationRecord, RecordKind, ScriptOutput, StatusMark,
)

ARCHIVE_ROOT = Path(__file__).resolve().parents[1] / ".vacuumforge_archive"
SCRIPT_ID = f"{Path(__file__).parent.name}__{Path(__file__).stem}"


def header(title: str) -> None:
    print()
    print("=" * 120)
    print(title)
    print("=" * 120)


def prepare_archive(dependencies):
    archive = ProjectArchive(ARCHIVE_ROOT)
    ns = archive.script_namespace(SCRIPT_ID)
    invalidated = ns.check_source_invalidation(__file__)
    for dep_id, upstream_script_id, upstream_derivation_id in dependencies:
        ns.declare_dependency(
            dependency_id=dep_id,
            upstream_script_id=upstream_script_id,
            upstream_derivation_id=upstream_derivation_id,
        )
    return archive, ns, invalidated


def print_archive_status(ns, invalidated: bool) -> None:
    if invalidated:
        print("[INFO] Archive invalidated due to source change.")
    checks = ns.verify_dependencies()
    if not checks:
        print("[INFO] Archive dependencies: none declared.")
        return
    print("[INFO] Archive dependency check:")
    for check in checks:
        print(f"  - {check.dependency.dependency_id}: {check.status} ({check.message})")


def record_marker(ns, marker_id: str, scope: str) -> None:
    ns.record_derivation(
        derivation_id=marker_id,
        inputs=[],
        output=sp.Symbol(marker_id),
        method="inventory marker; no physical derivation",
        status=Status.DERIVED,
        record_kind=RecordKind.INVENTORY_MARKER,
        is_placeholder=True,
        scope=scope,
    )


def record_claim(ns, marker_id: str, claim_id: str, status: GovernanceStatus, statement: str) -> None:
    ns.record_claim(
        ClaimRecord(
            claim_id=claim_id,
            script_id=SCRIPT_ID,
            claim_kind=RecordKind.GOVERNANCE_CLAIM,
            tier=ClaimTier.CONSTRAINED,
            status=status,
            statement=statement,
            derivation_ids=[marker_id],
            obligation_ids=[],
        )
    )


def record_obligation(ns, obligation_id: str, statement: str, status: ObligationStatus = ObligationStatus.OPEN) -> None:
    ns.record_obligation(
        ProofObligationRecord(
            obligation_id=obligation_id,
            script_id=SCRIPT_ID,
            title=obligation_id,
            status=status,
            required_by=[SCRIPT_ID],
            description=statement,
        )
    )


DEPENDENCIES = [
    ("g72_summary", "72_layer_term_legitimacy_audit__candidate_group_72_status_summary", "g72_summary"),
    ("g73_problem", "73_layer_generator_construction__candidate_layer_generator_problem", "g73_problem"),
]
MARKER_ID = "g73_requirements"


def main():
    archive, ns, invalidated = prepare_archive(DEPENDENCIES)
    print_archive_status(ns, invalidated)
    out = ScriptOutput()

    D_jump, D_layer, D_tail, L_bulk, L_gauge = sp.symbols("D_jump D_layer D_tail L_bulk L_gauge")
    B = sp.simplify(D_jump + D_layer + D_tail)
    L_boundary_ideal = sp.simplify(-B)
    residual = sp.simplify(B + L_boundary_ideal + L_bulk + L_gauge)

    criteria = [
        "geometric before coefficient choice",
        "local to boundary/layer region",
        "supplies D_layer as boundary component",
        "not diagnostic transition payload",
        "not ordinary-source carrying",
        "not trace carrying",
        "not mass response",
        "not repair current",
        "not active O by label",
        "compatible with common boundary object",
    ]

    header("Candidate Geometric Layer Generator Requirements")
    print(f"B = {B}")
    print(f"ideal L_boundary = {L_boundary_ideal}")
    print(f"ideal residual after boundary anti-match = {residual}")
    print("\nLegal geometric D_layer generator criteria:")
    for item in criteria:
        print(f"  - {item}")

    with out.derived_results():
        out.line("boundary sum", StatusMark.PASS, f"B={B}")
        out.line("ideal anti-match residual", StatusMark.PASS, str(residual))
    with out.governance_assessments():
        out.line("requirement", StatusMark.INFO, "D_layer must be generated by geometry, not selected or imported")
        out.line("bulk/gauge", StatusMark.OBLIGATION, "ideal boundary anti-match still leaves lift-cleanliness obligations")
    with out.counterexamples():
        out.line("diagnostic import", StatusMark.FAIL, "diagnostic transition material cannot be D_layer")
        out.line("repair current", StatusMark.FAIL, "after-the-fact cancellation is not layer-generator legitimacy")
        out.line("payload route", StatusMark.FAIL, "D_layer cannot carry source, trace, or mass payload")
    with out.unresolved_obligations():
        out.line("geometric origin", StatusMark.OBLIGATION, "construct or reject geometric D_layer origin")

    ns.record_derivation(
        derivation_id=MARKER_ID,
        inputs=[],
        output=residual,
        method="record legal D_layer criteria and ideal residual after boundary anti-match",
        status=Status.DERIVED,
        record_kind=RecordKind.COMPATIBILITY_EXAMPLE,
        result_type="layer_generator_requirements",
        scope="requirements; not D_layer theorem",
    )
    record_claim(ns, MARKER_ID, "g73_req_c1", GovernanceStatus.POLICY_RULE, "A legal D_layer must be generated by boundary/layer geometry before coefficient choice.")
    record_claim(ns, MARKER_ID, "g73_req_c2", GovernanceStatus.REJECTED_ROUTE, "Diagnostic, repair, source, trace, mass, and active-O payload routes are rejected.")
    record_obligation(ns, "g73_req_o1", "Derive D_layer from geometric layer generator or classify obstruction.")
    ns.write_run_metadata()
    print("\nPossible next script:")
    print("  candidate_signed_distance_layer_scaffold.py")


if __name__ == "__main__":
    main()
