"""Markdown report generation for VacuumForge.

Generates human-readable reports for validations, derivations,
failures, and model summaries.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import sympy

if TYPE_CHECKING:
    from vacuumforge.core.context import TheoryContext
    from vacuumforge.requirements.validators import ValidationResult


def md_math(expr: sympy.Basic) -> str:
    """Render a SymPy expression as a markdown math block."""
    return f"$$\n{sympy.latex(expr)}\n$$"


def md_inline_math(expr: sympy.Basic) -> str:
    """Render a SymPy expression as inline math."""
    return f"${sympy.latex(expr)}$"


# --- Failure codes ---

FAILURE_CODES = {
    "KAPPA_SOURCED": "kappa is sourced (J_kappa != 0), preventing kappa = 0",
    "GAMMA_REMAINS_FREE": "gamma_v remains a free parameter",
    "POSITIVITY_UNDETERMINED": "Energy positivity could not be determined",
    "TARGET_ASSUMED": "Target result was assumed, not derived",
    "ONLY_FIRST_ORDER": "Result holds only to first order, not exactly",
    "COORDINATE_SCOPE_LIMITED": "Result applies only in restricted coordinate scope",
    "TRACE_FREE_NOT_DERIVED": "Trace-free exchange was assumed, not derived",
}


def generate_validation_report(
    ctx: TheoryContext,
    results: list[ValidationResult],
) -> str:
    """Generate a markdown validation report."""
    lines = []
    lines.append(f"# Validation Report: {ctx.name}")
    lines.append("")

    # Assumptions
    lines.append("## Active Assumptions")
    lines.append("")
    assumptions = ctx.assumptions.active()
    if assumptions:
        for a in assumptions:
            expr_str = md_inline_math(a.expression) if hasattr(a.expression, 'free_symbols') else str(a.expression)
            lines.append(f"- **{a.id}**: {expr_str}")
    else:
        lines.append("_None declared._")
    lines.append("")

    # Sources
    lines.append("## Source Configuration")
    lines.append("")
    sources = ctx.sources.list()
    if sources:
        for s in sources:
            lines.append(f"- **{s.id}** ({s.source_type}): {s.classification.value}")
            if s.J_kappa is not None:
                lines.append(f"  - $J_\\kappa = {sympy.latex(s.J_kappa)}$")
            if s.J_sigma is not None:
                lines.append(f"  - $J_\\sigma = {sympy.latex(s.J_sigma)}$")
    else:
        lines.append("_No sources defined._")
    lines.append("")

    # Energy
    lines.append("## Energy Functionals")
    lines.append("")
    functionals = ctx.energy.list()
    if functionals:
        for f in functionals:
            lines.append(f"- **{f.id}**:")
            lines.append(md_math(f.expression))
    else:
        lines.append("_No energy functional defined._")
    lines.append("")

    # Validation results
    lines.append("## Requirement Validation")
    lines.append("")
    lines.append("| Requirement | Status | Details |")
    lines.append("|---|---|---|")

    status_icons = {"pass": "PASS", "fail": "FAIL", "assumed": "ASSUMED", "undetermined": "?"}

    for r in results:
        icon = status_icons.get(r.status, "?")
        lines.append(f"| {r.requirement_id} | **{icon}** | {r.message} |")
    lines.append("")

    # Failure analysis
    failures = [r for r in results if r.status == "fail"]
    assumed = [r for r in results if r.status == "assumed"]

    if failures:
        lines.append("## Failures")
        lines.append("")
        for f in failures:
            lines.append(f"### {f.requirement_id}")
            lines.append("")
            lines.append(f"{f.message}")
            if f.evidence:
                for e in f.evidence:
                    lines.append(f"- Evidence: {md_inline_math(e)}")
            lines.append("")

    if assumed:
        lines.append("## Assumption Warnings")
        lines.append("")
        for a in assumed:
            lines.append(f"- **{a.requirement_id}**: {a.message}")
        lines.append("")

    # Summary
    n_pass = len([r for r in results if r.status == "pass"])
    n_fail = len(failures)
    n_assumed = len(assumed)
    n_undet = len([r for r in results if r.status == "undetermined"])

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Pass: {n_pass}")
    lines.append(f"- Fail: {n_fail}")
    lines.append(f"- Assumed: {n_assumed}")
    lines.append(f"- Undetermined: {n_undet}")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by VacuumForge_")

    return "\n".join(lines)


def generate_model_summary(ctx: TheoryContext) -> str:
    """Generate a markdown model summary."""
    lines = []
    lines.append(f"# Model Summary: {ctx.name}")
    lines.append("")

    lines.append("## Symbols")
    lines.append("")
    for kind in ["constant", "coordinate", "scale_factor", "log_variable",
                  "mode", "potential", "source", "coefficient"]:
        records = ctx.symbols.list(kind)
        if records:
            lines.append(f"### {kind.replace('_', ' ').title()}s")
            for r in records:
                desc = f" — {r.description}" if r.description else ""
                lines.append(f"- `{r.name}`{desc}")
            lines.append("")

    lines.append("## Definitions")
    lines.append("")
    for expr_rec in ctx.expressions.list():
        if expr_rec.status == "definition":
            lines.append(f"- **{expr_rec.id}**: {md_inline_math(expr_rec.expr)}")
    lines.append("")

    return "\n".join(lines)


class ReportManager:
    """Manages report generation for a theory context."""

    def __init__(self, ctx: TheoryContext) -> None:
        self._ctx = ctx

    def validation(self, results: list[ValidationResult] | None = None) -> _ReportHandle:
        if results is None:
            results = self._ctx.requirements.validate_all(self._ctx)
        content = generate_validation_report(self._ctx, results)
        return _ReportHandle(content)

    def model_summary(self) -> _ReportHandle:
        content = generate_model_summary(self._ctx)
        return _ReportHandle(content)


class _ReportHandle:
    """Handle for a generated report."""

    def __init__(self, content: str) -> None:
        self.content = content

    def to_markdown(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.content)

    def __str__(self) -> str:
        return self.content
