#!/usr/bin/env python3
"""
make_9_rotational_defect_requires_holonomy_channel.py

Validate that a rotational defect/torsion source requires an antisymmetric
holonomy or closure-failure channel.

Output:
    9_rotational_defect_requires_holonomy_channel.md
"""

from pathlib import Path
import sympy as sp


def simplify_expr(expr):
    return sp.factor(sp.cancel(sp.simplify(expr)))


def require_zero(label, expr):
    result = simplify_expr(expr)
    if result != 0:
        raise AssertionError(f"{label} failed:\n{result}")


a, b, c, d, kappa = sp.symbols("a b c d kappa")

M = sp.Matrix([[a, b], [c, d]])
S = simplify_expr((M + M.T) / 2)
A = simplify_expr((M - M.T) / 2)

theta = simplify_expr((c - b) / 2)
J_defect = simplify_expr(kappa * theta)

require_zero("antisymmetric component A12", A[0, 1] + theta)
require_zero("antisymmetric component A21", A[1, 0] - theta)
require_zero("symmetric part has no antisymmetric component", S[0, 1] - S[1, 0])
require_zero("no holonomy residual when b=c", J_defect.subs(c, b))

defect_witness = simplify_expr(sp.diff(J_defect, c) - sp.diff(J_defect, b))
require_zero("defect witness", defect_witness - kappa)

md = f"""# Torsion Defect Exclusion 9: Rotational Defect Requires Holonomy Channel

## Purpose

This proof checks the route for rotational/closure-failure torsion sources.

A rotational defect requires antisymmetric holonomy data. Symmetric deformation
data is not enough.

## Validated Checks

- antisymmetric part of a local comparison map carries the rotation: passed
- symmetric part has no antisymmetric component: passed
- if the holonomy/closure residual vanishes, the defect source vanishes: passed

## Model

For a local comparison map:

```text
M = [[a,b],[c,d]],
```

the antisymmetric component is:

```text
A = (M-M^T)/2.
```

The rotation/closure witness is:

```text
theta = (c-b)/2.
```

A defect source of the form:

```text
J_defect = kappa theta
```

vanishes when:

```text
b = c.
```

## Interpretation

Rotational defect torsion is not generated by symmetric interval data. It
requires an independent holonomy, closure-failure, or orientation-rotation
channel.
"""

out = Path(__file__).with_name("9_rotational_defect_requires_holonomy_channel.md")
tmp = out.with_suffix(out.suffix + ".tmp")
tmp.write_text(md, encoding="utf-8")
tmp.replace(out)

print("Rotational defect holonomy-channel gate passed.")
print(f"Wrote {out.resolve()}")

