# Group:
#   05_nonspherical_sectors
#
# Script type:
#   DIAGNOSTIC

# Candidate vector sector frame dragging
#
# Purpose
# -------
# The nonspherical degree inventory shows that scalar A handles the weak
# Newtonian scalar sector, but cannot produce off-diagonal components:
#
#   g_ti != 0
#
# These are needed for rotating sources, gravitomagnetism, and frame dragging.
#
# This script tests a reduced weak vector-sector candidate:
#
#   g_ti ~ vector potential W_i
#
# analogous to a weak gravitomagnetic vector potential.
#
# It does not derive the full GR frame-dragging equation. It checks:
#
#   1. scalar A cannot create g_ti,
#   2. a vector W_i is a distinct sector,
#   3. rotational sources require an angular-momentum-like source,
#   4. exterior dipole-like vector potential carries angular momentum,
#   5. curl W gives a frame-dragging-like field,
#   6. this sector must be added beyond scalar A/kappa.

from pathlib import Path

import sympy as sp

from vacuumforge import ProjectArchive, Status
from vacuumforge.governance import (
    ClaimRecord,
    ClaimTier,
    GovernanceStatus,
    ObligationStatus,
    ProofObligationRecord,
    RecordKind,
    RouteRecord,
    ScriptOutput,
    StatusMark,
)


ARCHIVE_ROOT = Path(__file__).resolve().parents[1] / ".vacuumforge_archive"
SCRIPT_ID = f"{Path(__file__).parent.name}__{Path(__file__).stem}"


# =============================================================================
# Utilities
# =============================================================================

def header(title: str) -> None:
    print()
    print("=" * 116)
    print(title)
    print("=" * 116)


def is_zero(expr) -> bool:
    try:
        return bool(sp.simplify(expr) == 0)
    except Exception:
        return False


def prepare_archive():
    archive = ProjectArchive(ARCHIVE_ROOT)
    ns = archive.script_namespace(SCRIPT_ID)
    invalidated = ns.check_source_invalidation(__file__)
    ns.declare_dependency(
        dependency_id="trace_free_spatial_shear_inventory",
        upstream_script_id="005_nonspherical_sectors__candidate_nonspherical_degree_inventory",
        upstream_derivation_id="trace_free_spatial_shear_inventory",
    )
    return archive, ns, invalidated


def print_archive_status(ns, invalidated: bool) -> None:
    if invalidated:
        print("[INFO] Archive invalidated due to source change.")
    checks = ns.verify_dependencies()
    if not checks:
        print("[INFO] Archive dependencies: none declared.")
        return
    print("[INFO] Archive dependency check:")
    for check in checks:
        print(f"  - {check.dependency.dependency_id}: {check.status} ({check.message})")


def curl_cartesian(V, x, y, z):
    Vx, Vy, Vz = V
    return sp.Matrix([
        sp.diff(Vz, y) - sp.diff(Vy, z),
        sp.diff(Vx, z) - sp.diff(Vz, x),
        sp.diff(Vy, x) - sp.diff(Vx, y),
    ])


# =============================================================================
# Case 0: Why vector sector is needed
# =============================================================================

def case_0_problem_statement():
    header("Case 0: Why vector sector is needed")

    print("Scalar sector:")
    print("  A = 1 + 2 Phi/c^2")
    print("  spatial scalar factor ≈ 1 - 2 Phi/c^2")
    print()
    print("But rotating sources require:")
    print("  g_ti != 0")
    print()
    print("These components are not generated by scalar A or kappa alone.")
    print()

    out = ScriptOutput()
    with out.unresolved_obligations():
        out.line("frame dragging requires additional vector sector", StatusMark.OBLIGATION, "g_ti not produced by scalar A")


# =============================================================================
# Case 1: Scalar metric has no g_ti
# =============================================================================

def case_1_scalar_metric_no_vector():
    header("Case 1: Scalar metric has no g_ti")

    psi = sp.symbols("psi", real=True)

    # Weak scalar metric perturbation in block form:
    # h_tt = -2 psi (up to sign convention), h_ti=0, h_ij=-2psi delta_ij.
    h_ti = sp.Matrix([[0, 0, 0]])

    print("Weak scalar metric has:")
    print(f"  h_ti = {h_ti}")
    print()
    print("Therefore scalar A cannot represent frame dragging.")

    out = ScriptOutput()
    with out.derived_results():
        out.line("scalar sector has zero vector components", StatusMark.PASS, "h_ti = 0 for scalar A")


# =============================================================================
# Case 2: Introduce vector potential W_i
# =============================================================================

def case_2_introduce_vector_potential():
    header("Case 2: Introduce vector potential W_i")

    Wx, Wy, Wz = sp.symbols("W_x W_y W_z", real=True)
    W = sp.Matrix([[Wx, Wy, Wz]])

    print("Candidate vector sector:")
    print()
    print("  g_ti contains W_i")
    print()
    print(f"W_i = {W}")
    print()
    print("Interpretation:")
    print("  W_i is independent of scalar A.")
    print("  It should be sourced by mass current / angular momentum.")

    out = ScriptOutput()
    with out.governance_assessments():
        out.line("vector potential sector introduced", StatusMark.PASS, "W_i distinct from scalar A")


# =============================================================================
# Case 3: Rotating source requires angular momentum source
# =============================================================================

def case_3_angular_momentum_source():
    header("Case 3: Angular momentum source")

    Jx, Jy, Jz = sp.symbols("J_x J_y J_z", real=True)
    J = sp.Matrix([Jx, Jy, Jz])

    print("Rotating source characterized by angular momentum vector:")
    print()
    print(f"J = {J}")
    print()
    print("Scalar mass M sources A-flux.")
    print("Angular momentum J should source vector sector W_i.")
    print()
    print("This separates:")
    print("  density / mass -> scalar A")
    print("  mass current / spin -> vector W_i")

    out = ScriptOutput()
    with out.governance_assessments():
        out.line("source channel separation formulated", StatusMark.PASS, "M -> scalar A; J -> vector W_i")


# =============================================================================
# Case 4: Dipole-like exterior vector potential
# =============================================================================

def case_4_dipole_vector_potential(ns):
    header("Case 4: Dipole-like exterior vector potential")

    x, y, z, J = sp.symbols("x y z J", real=True)
    r = sp.sqrt(x**2 + y**2 + z**2)

    # Choose angular momentum along z: J_vec = J zhat.
    # A dipole-like vector potential proportional to J x r / r^3.
    # J_vec x r_vec = (-J y, J x, 0)
    W = sp.Matrix([
        -J*y/r**3,
        J*x/r**3,
        0
    ])

    curlW = sp.simplify(curl_cartesian(W, x, y, z))

    print("For angular momentum along z:")
    print("  J_vec x r_vec = (-J y, J x, 0)")
    print()
    print("Candidate exterior vector potential:")
    print(f"W = {W}")
    print()
    print("curl(W) =")
    print(curlW)

    curl_nonzero = not all(is_zero(c) for c in curlW)
    out = ScriptOutput()
    with out.derived_results():
        out.line("dipole-like vector potential has nonzero curl",
                 StatusMark.PASS if curl_nonzero else StatusMark.FAIL,
                 f"curl W = {curlW}")

    ns.record_derivation(
        derivation_id="dipole_vector_potential_curl",
        inputs=[W[0], W[1], W[2]],
        output=curlW,
        method="curl_cartesian_dipole_vector_potential",
        status=Status.DERIVED,
        record_kind=RecordKind.DIAGNOSTIC_EXAMPLE,
        scope="dipole-like vector potential for J along z",
    )


# =============================================================================
# Case 5: Vector potential has zero scalar monopole flux
# =============================================================================

def case_5_no_scalar_flux_confusion():
    header("Case 5: Vector sector does not alter scalar A-flux directly")

    print("The vector sector should not be confused with scalar A-flux.")
    print()
    print("Scalar A-flux:")
    print("  F_A = integral grad(A) · dS")
    print()
    print("Vector/frame-dragging sector:")
    print("  sourced by mass current/angular momentum")
    print("  encoded in g_ti-like components")
    print()
    print("Thus:")
    print("  M controls scalar A-flux")
    print("  J controls vector W_i")
    print()

    out = ScriptOutput()
    with out.governance_assessments():
        out.line("scalar and vector flux/source channels separated", StatusMark.PASS, "M -> A-flux; J -> W_i")


# =============================================================================
# Case 6: Candidate weak vector field equation
# =============================================================================

def case_6_candidate_vector_equation():
    header("Case 6: Candidate weak vector equation")

    print("A minimal weak vector-sector analogy would be:")
    print()
    print("  ∇² W_i = source_i")
    print()
    print("where source_i is related to mass current density.")
    print()
    print("In source-free exterior:")
    print()
    print("  ∇² W_i = 0")
    print()
    print("Rotating compact sources would produce dipole-like W_i terms.")
    print()
    print("This is only a placeholder. Normalization and covariance are open.")

    out = ScriptOutput()
    with out.unresolved_obligations():
        out.line("candidate vector equation class identified", StatusMark.OBLIGATION, "normalization and covariance remain open")


# =============================================================================
# Case 7: What this sector must eventually reproduce
# =============================================================================

def case_7_targets():
    header("Case 7: Vector-sector targets")

    print("A viable vector sector should eventually reproduce:")
    print()
    print("1. weak gravitomagnetic effects,")
    print("2. frame dragging by rotating bodies,")
    print("3. correct angular-momentum falloff,")
    print("4. no contamination of scalar mass flux,")
    print("5. gauge-aware treatment of vector potentials,")
    print("6. coupling to moving matter / mass current.")
    print()

    out = ScriptOutput()
    with out.unresolved_obligations():
        out.line("vector-sector target list established", StatusMark.OBLIGATION, "normalization, gauge structure, and covariant parent remain open")


# =============================================================================
# Case 8: Classification
# =============================================================================

def case_8_classification():
    header("Case 8: Classification")

    print("Results:")
    print()
    print("1. Scalar A has no g_ti components.")
    print("2. Frame dragging requires an independent vector sector.")
    print("3. Mass M should source scalar A-flux.")
    print("4. Angular momentum / mass current should source vector W_i.")
    print("5. A dipole-like exterior vector potential has nonzero curl.")
    print("6. A weak vector Poisson/Laplace class is a plausible first placeholder.")
    print("7. Normalization, gauge structure, and covariant parent remain open.")
    print()

    out = ScriptOutput()
    with out.governance_assessments():
        out.line("vector sector is necessary but not yet derived", StatusMark.DEFER, "required but normalization/covariance open")


# =============================================================================
# Final interpretation
# =============================================================================

def final_interpretation():
    header("Final interpretation")

    print("The scalar A branch cannot reproduce frame dragging.")
    print()
    print("A separate weak vector sector W_i is needed for g_ti components.")
    print("The natural source is mass current or angular momentum, not scalar mass.")
    print()
    print("This keeps source channels separated:")
    print()
    print("  mass / density -> scalar A-flux")
    print("  trace / pressure -> kappa/interior response")
    print("  angular momentum / mass current -> vector W_i")
    print()
    print("Possible next artifact:")
    print("  candidate_vector_sector_frame_dragging.md")
    print()
    print("Possible later script:")
    print("  candidate_wave_sector_linearized_modes.py")


def main():
    header("Candidate Vector Sector Frame Dragging")
    archive, ns, invalidated = prepare_archive()
    print_archive_status(ns, invalidated)
    case_0_problem_statement()
    case_1_scalar_metric_no_vector()
    case_2_introduce_vector_potential()
    case_3_angular_momentum_source()
    case_4_dipole_vector_potential(ns)
    case_5_no_scalar_flux_confusion()
    case_6_candidate_vector_equation()
    case_7_targets()
    case_8_classification()
    final_interpretation()

    ns.record_obligation(ProofObligationRecord(
        obligation_id="derive_vector_sector_normalization",
        script_id=SCRIPT_ID,
        title="Derive vector sector normalization and covariant parent",
        status=ObligationStatus.OPEN,
        description=(
            "The weak vector Laplace-class equation for W_i is a placeholder. "
            "Normalization (coupling to mass current), gauge structure, and a "
            "covariant parent field equation must be derived."
        ),
    ))

    ns.record_claim(ClaimRecord(
        claim_id="vector_sector_required_and_separate",
        script_id=SCRIPT_ID,
        claim_kind=RecordKind.GOVERNANCE_CLAIM,
        tier=ClaimTier.CONSTRAINED,
        status=GovernanceStatus.POLICY_RULE,
        statement=(
            "Scalar A cannot produce g_ti frame-dragging components. A separate vector "
            "sector W_i is required, sourced by angular momentum / mass current, and must "
            "not contaminate the scalar A-flux mass channel."
        ),
        obligation_ids=["derive_vector_sector_normalization"],
    ))

    ns.record_route(RouteRecord(
        route_id="vector_sector_weak_laplace_route",
        script_id=SCRIPT_ID,
        name="Weak vector Laplace sector for frame dragging",
        status=GovernanceStatus.CANDIDATE_ROUTE,
        tier=ClaimTier.CONSTRAINED,
        required_obligations=["derive_vector_sector_normalization"],
        activation_conditions=[
            "vector W_i sourced by mass current / angular momentum",
            "exterior satisfies Laplace equation",
            "no contamination of scalar A-flux",
        ],
    ))

    ns.record_derivation(
        derivation_id="vector_sector_inventory_marker",
        inputs=[],
        output=sp.Symbol("vector_sector_required"),
        method="vector_sector_inventory",
        status=Status.DERIVED,
        record_kind=RecordKind.INVENTORY_MARKER,
        is_placeholder=True,
    )
    ns.write_run_metadata()


if __name__ == "__main__":
    main()
