#!/usr/bin/env python3
from pathlib import Path
import sympy as sp

OUT = Path(__file__).with_name("11_news_from_tt_derivative_gate.md")

def require_zero(expr, label):
    val = sp.simplify(expr)
    if val != 0:
        raise AssertionError(f"{label} expected zero, got {val}")

def require_equal(a, b, label):
    diff = sp.simplify(a-b)
    if diff != 0:
        raise AssertionError(f"{label} expected equality, got diff {diff}")

def require_nonzero(expr, label):
    val = sp.simplify(expr)
    if val == 0:
        raise AssertionError(f"{label} expected nonzero")

def write_md(text):
    tmp = OUT.with_suffix('.md.tmp')
    tmp.write_text(text, encoding='utf-8')
    tmp.replace(OUT)


u,A,w=sp.symbols('u A w', nonzero=True)
h=A*sp.cos(w*u)
N=sp.diff(h,u)
require_equal(N, -A*w*sp.sin(w*u), 'news derivative')
flux=sp.simplify(N**2)
require_nonzero(flux,'news flux')


write_md('# 11. News from TT derivative gate\n\nBoundary news is modeled as a retarded-time derivative of shear/TT strain:\n\n```text\nh(u) = A cos(wu),\nN(u) = ∂_u h = -A w sin(wu).\n```\n\nValidated check:\n\n```text\nN^2 != 0\n```\n\nResult: radiative boundary flux is generated by tensor-time variation, not scalar monopole charge.\n')
