"""Report generation for structure search results."""

from __future__ import annotations

import sympy

from vacuumforge.structure_search.results import (
    InducedModeSource,
    StructureAnalysisResult,
    StructureStatus,
)
from vacuumforge.structure_search.structure import VacuumStructure


def generate_structure_report(
    structure: VacuumStructure,
    result: StructureAnalysisResult,
) -> str:
    """Generate a markdown report for a structure analysis."""
    lines = []
    lines.append(f"# Structure Search Analysis: {structure.id}")
    lines.append("")

    if structure.description:
        lines.append(f"_{structure.description}_")
        lines.append("")

    # Variables
    lines.append("## Pre-Mode Variables")
    lines.append("")
    for v in structure.variables:
        lines.append(f"- ${sympy.latex(v)}$")
    lines.append("")

    # Projection map
    lines.append("## Projection Map")
    lines.append("")
    lines.append(f"$$a = {sympy.latex(structure.projection.a_expr)}$$")
    lines.append(f"$$b = {sympy.latex(structure.projection.b_expr)}$$")
    lines.append("")

    if structure.projection.is_linear():
        lines.append("Projection is **linear**.")
    else:
        lines.append("Projection is **nonlinear**.")
        lines.append("")
        lines.append("Jacobian:")
        lines.append(f"$${sympy.latex(structure.projection.jacobian())}$$")
    lines.append("")

    # Exchange operators
    lines.append("## Exchange Operators")
    lines.append("")
    for op in structure.exchange_operators:
        lines.append(f"### {op.id}")
        if op.description:
            lines.append(f"_{op.description}_")
        lines.append("")
        for var, delta in op.deltas.items():
            lines.append(f"- $\\delta {sympy.latex(var)} = {sympy.latex(delta)}$")
        lines.append("")

    # Creation operators
    lines.append("## Creation Operators")
    lines.append("")
    for op in structure.creation_operators:
        lines.append(f"### {op.id}")
        if op.description:
            lines.append(f"_{op.description}_")
        lines.append("")
        for var, delta in op.deltas.items():
            lines.append(f"- $\\delta {sympy.latex(var)} = {sympy.latex(delta)}$")
        lines.append("")

    # Induced sources
    lines.append("## Induced Source Analysis")
    lines.append("")

    for induced in result.exchange_results + result.creation_results:
        lines.append(f"### {induced.operator_id} ({induced.operator_kind})")
        lines.append("")
        lines.append(f"- $J_a = {sympy.latex(induced.J_a)}$")
        lines.append(f"- $J_b = {sympy.latex(induced.J_b)}$")
        lines.append(f"- $J_\\kappa = {sympy.latex(induced.J_kappa)}$")
        lines.append(f"- $J_\\sigma = {sympy.latex(induced.J_sigma)}$")
        lines.append(f"- **Classification**: {induced.classification}")
        lines.append(f"- **Status**: {induced.status.value}")
        lines.append("")

        if induced.conditions:
            lines.append("**Conditions:**")
            for c in induced.conditions:
                lines.append(f"- ${sympy.latex(c)}$")
            lines.append("")

        if induced.notes:
            lines.append("**Notes:**")
            for note in induced.notes:
                lines.append(f"- {note}")
            lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")

    status_label = {
        StructureStatus.DERIVED: "DERIVED",
        StructureStatus.ASSUMED: "ASSUMED",
        StructureStatus.CONDITIONAL: "CONDITIONAL",
        StructureStatus.FAILED: "FAILED",
        StructureStatus.UNDETERMINED: "UNDETERMINED",
        StructureStatus.TAUTOLOGICAL: "TAUTOLOGICAL",
    }

    lines.append(f"**Overall Status**: {status_label.get(result.summary_status, '?')}")
    lines.append(f"- Trace-free exchange derived: {'Yes' if result.derived_trace_free_exchange else 'No'}")
    lines.append(f"- Traceful creation derived: {'Yes' if result.derived_traceful_creation else 'No'}")
    lines.append("")

    if result.conditions:
        lines.append("### Required Conditions")
        for c in result.conditions:
            lines.append(f"- ${sympy.latex(c)}$")
        lines.append("")

    if result.failures:
        lines.append("### Failures")
        for f in result.failures:
            lines.append(f"- {f}")
        lines.append("")

    if result.leak_warnings:
        lines.append("### Assumption Leak Warnings")
        for w in result.leak_warnings:
            lines.append(f"- {w}")
        lines.append("")

    if result.notes:
        lines.append("### Notes")
        for n in result.notes:
            lines.append(f"- {n}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by VacuumForge StructureSearch_")

    return "\n".join(lines)
