#!/usr/bin/env python3
"""
make_51_nonlinear_correction_power_law.py

Classify the first weak-field correction generated by nonlinear strain
densities of the form:

    Phi_p(z) = 1/2 z + alpha/(2p) z^p.

In 3D radial flux form, the first correction to u(r) scales as:

    r^(-(4p-3)).

Output:
    51_nonlinear_correction_power_law.md
"""

from pathlib import Path
import sympy as sp


r = sp.symbols("r", positive=True)
Q, alpha = sp.symbols("Q alpha", real=True)
pi = sp.pi


def require_zero(label, expr):
    result = sp.simplify(sp.factor(expr))
    if result != 0:
        raise AssertionError(f"{label} failed:\n{result}")


def require_equal(label, lhs, rhs):
    require_zero(label, lhs - rhs)


checks = []
rows = []

for p in range(2, 8):
    y0 = Q / (4 * pi * r**2)
    y_approx = y0 - alpha * y0 ** (2 * p - 1)

    # Flux law from Phi_p:
    #   Q = 4*pi*r^2(y + alpha*y^(2p-1)).
    flux_residual = sp.expand(4 * pi * r**2 * (y_approx + alpha * y_approx ** (2 * p - 1)) - Q)
    require_zero(
        f"p={p} perturbative flux residual through first order",
        sp.series(flux_residual, alpha, 0, 2).removeO(),
    )

    correction_power = 4 * p - 3
    C = Q / (4 * pi)
    u_approx = C / r - alpha * C ** (2 * p - 1) / (correction_power * r**correction_power)

    y_from_u = -sp.diff(u_approx, r)
    require_zero(
        f"p={p} potential derivative matches perturbative y",
        sp.series(y_from_u - y_approx, alpha, 0, 2).removeO(),
    )

    scaled_correction = sp.simplify((u_approx - C / r) * r**correction_power / alpha)
    require_equal(
        f"p={p} correction coefficient",
        scaled_correction,
        -C ** (2 * p - 1) / correction_power,
    )

    rows.append((p, correction_power, sp.sstr(sp.factor(scaled_correction))))

checks.append("Phi_p correction law verified for p=2..7")

row_lines = "\n".join(
    f"p={p}: correction power r^-{power}, coefficient {coeff}"
    for p, power, coeff in rows
)
validation_bullets = "\n".join("- " + item + ": passed" for item in checks)

md = f"""# Boundary Flux Field Bridge 51: Nonlinear Correction Power Law

## Purpose

This report classifies the first weak-field correction generated by nonlinear
radial strain densities:

```text
Phi_p(z) = 1/2 z + alpha/(2p) z^p.
```

The Dirichlet model is recovered at `alpha=0`.

## Validated Checks

{validation_bullets}

## Flux Law

Let:

```text
y = -u' > 0.
```

For `Phi_p`, the radial flux law is:

```text
Q = 4*pi*r^2 [y + alpha y^(2p-1)].
```

With:

```text
y0 = Q/(4*pi*r^2),
```

the first-order perturbative solution is:

```text
y = y0 - alpha y0^(2p-1) + O(alpha^2).
```

Integrating from infinity gives:

```text
u(r)
  =
  Q/(4*pi*r)
  - alpha (Q/(4*pi))^(2p-1) / [(4p-3) r^(4p-3)]
  + O(alpha^2).
```

## Checked Cases

```text
{row_lines}
```

## Interpretation

The first nonlinear correction has a definite power:

```text
r^(-(4p-3)).
```

For `p=2`, this recovers proof `44`:

```text
r^-5.
```

This gives a compact classifier for candidate nonlinear scalar vacuum energies.
Each nonlinear strain power predicts a different far-field correction hierarchy.
"""

out = Path(__file__).with_name("51_nonlinear_correction_power_law.md")
out.write_text(md, encoding="utf-8")

print("All symbolic checks passed.")
print(f"Wrote {out.resolve()}")
