#!/usr/bin/env python3
"""
make_47_bulk_source_boundary_flux_equivalence.py

Validate that a compact spherically symmetric bulk source and an enclosing
boundary flux give the same exterior field.

Output:
    47_bulk_source_boundary_flux_equivalence.md
"""

from pathlib import Path
import sympy as sp


r, R = sp.symbols("r R", positive=True)
rho0, rho2, rho4 = sp.symbols("rho0 rho2 rho4", real=True)
pi = sp.pi


def require_zero(label, expr):
    result = sp.simplify(sp.factor(expr))
    if result != 0:
        raise AssertionError(f"{label} failed:\n{result}")


def require_equal(label, lhs, rhs):
    require_zero(label, lhs - rhs)


checks = []

# A representative compact radial bulk source inside radius R.
rho = rho0 + rho2 * r**2 + rho4 * r**4
Q_total = sp.integrate(4 * pi * r**2 * rho, (r, 0, R))
Q_expected = 4 * pi * (rho0 * R**3 / 3 + rho2 * R**5 / 5 + rho4 * R**7 / 7)

require_equal("polynomial bulk source total charge", Q_total, Q_expected)
checks.append("polynomial bulk source total charge")

# Exterior field determined only by total enclosed source.
s = sp.symbols("s", positive=True)
u_ext = Q_total / (4 * pi * s)
lap_ext = sp.diff(u_ext, s, 2) + 2 * sp.diff(u_ext, s) / s
flux_ext = -4 * pi * s**2 * sp.diff(u_ext, s)

require_zero("exterior field is harmonic", lap_ext)
checks.append("exterior field is harmonic")
require_equal("exterior flux equals enclosed source", flux_ext, Q_total)
checks.append("exterior flux equals enclosed source")
require_zero("exterior flux is conserved", sp.diff(flux_ext, s))
checks.append("exterior flux is conserved")

# The same exterior field is generated by imposing boundary flux Q_total at R.
u_boundary = Q_total / (4 * pi * s)
boundary_flux = -4 * pi * R**2 * sp.diff(u_boundary, s).subs(s, R)
require_equal("boundary flux reproduces bulk source total", boundary_flux, Q_total)
checks.append("boundary flux reproduces bulk source total")

# Potential at the boundary is determined by total charge only.
boundary_potential = u_ext.subs(s, R)
require_equal("boundary potential from enclosed source", boundary_potential, Q_total / (4 * pi * R))
checks.append("boundary potential from enclosed source")


validation_bullets = "\n".join("- " + item + ": passed" for item in checks)

md = f"""# Boundary Flux Field Bridge 47: Bulk Source and Boundary Flux Equivalence

## Purpose

This report validates that, in the spherical exterior problem, a compact bulk
source and an enclosing boundary flux are equivalent outside the source region.

This is the standard shell/Gauss-law behavior, written in the bookkeeping used
by this branch.

## Validated Checks

{validation_bullets}

## Representative Bulk Source

Inside radius `R`, take:

```text
rho(r) = rho0 + rho2 r^2 + rho4 r^4.
```

The total enclosed source is:

```text
Q = 4*pi*(rho0 R^3/3 + rho2 R^5/5 + rho4 R^7/7).
```

## Exterior Field

For `r > R`, the exterior solution is:

```text
u(r) = Q/(4*pi*r).
```

SymPy verifies:

```text
Delta u = 0
-4*pi*r^2*u'(r) = Q.
```

## Boundary Flux Equivalence

The same exterior field is generated by imposing the boundary flux condition:

```text
-4*pi*R^2*u'(R) = Q.
```

Therefore:

```text
compact spherical bulk source
```

and:

```text
enclosing boundary flux
```

are equivalent for the exterior field.

## Interpretation

This supports the boundary-source reading without denying ordinary bulk-source
language. In the exterior vacuum problem, only the enclosed flux/charge matters.
"""

out = Path(__file__).with_name("47_bulk_source_boundary_flux_equivalence.md")
out.write_text(md, encoding="utf-8")

print("All symbolic checks passed.")
print(f"Wrote {out.resolve()}")
