# Trial 018: Closure uniqueness, step 10
#
# Script type:
#   RIGOR PROGRAM / HIGHER-H FIELD-REDEFINITION REDUCTION
#
# Purpose
# -------
# This is the tenth in-house rung toward replacing the Deser 1970
# self-coupled spin-2 closure citation. It still does not by itself
# retire the full closure-uniqueness obligation.
#
# Step 9 excluded every non-Palatini higher-H mismatch direction
# Hp.Rlin - Hp.Q. The only remaining derivative tower is the
# equal-coefficient direction
#
#       Hp.Rlin + Hp.Q.
#
# This script checks that the whole equal-coefficient tower is nonlinear
# metric-density field-redefinition freedom. For
#
#       K = H + sum_p a_p Hp,
#
# inserting K into the Palatini replacement gives
#
#       eta.(Rlin + Q) + H.(Rlin + Q)
#       + sum_p a_p Hp.(Rlin + Q).
#
# Therefore every surviving higher-H derivative term is a choice of
# nonlinear metric-density variable, not an inequivalent closure.

from pathlib import Path

import sympy as sp

from vacuumforge import ProjectArchive, Status
from vacuumforge.governance import (
    ClaimRecord,
    ClaimTier,
    GovernanceStatus,
    ObligationStatus,
    ProofObligationRecord,
    RecordKind,
    ScriptOutput,
    StatusMark,
)


ARCHIVE_ROOT = Path(__file__).resolve().parents[1] / ".vacuumforge_archive"
SCRIPT_ID = f"{Path(__file__).parent.name}__{Path(__file__).stem}"

SAMPLE_POWERS = [2, 3, 4, 5, 6]


def header(title: str) -> None:
    print()
    print("=" * 120)
    print(title)
    print("=" * 120)


def is_zero(expr) -> bool:
    try:
        return bool(sp.simplify(expr) == 0)
    except Exception:
        return False


def print_archive_status(ns, invalidated: bool) -> None:
    if invalidated:
        print("[INFO] Archive invalidated due to source change.")
    checks = ns.verify_dependencies()
    if not checks:
        print("[INFO] Archive dependencies: none declared.")
        return
    print("[INFO] Archive dependency check:")
    for check in checks:
        print(f"  - {check.dependency.dependency_id}: {check.status} ({check.message})")


def prepare_archive():
    archive = ProjectArchive(ARCHIVE_ROOT)
    ns = archive.script_namespace(SCRIPT_ID)
    invalidated = ns.check_source_invalidation(__file__)
    ns.declare_dependency(
        dependency_id="closure_step_9_dependency_018",
        upstream_script_id="018_closure_uniqueness__closure_step_9_higher_h_mismatch_lock",
        upstream_derivation_id="higher_h_mismatch_tower_excluded_018",
        expected_record_kind=RecordKind.DERIVATION,
    )
    ns.declare_dependency(
        dependency_id="closure_step_6_redefinition_dependency_018",
        upstream_script_id="018_closure_uniqueness__closure_step_6_field_redefinition_h2",
        upstream_derivation_id="h2_field_redefinition_locked_pair_018",
        expected_record_kind=RecordKind.DERIVATION,
    )
    return archive, ns, invalidated


a, c = sp.symbols("a c")
HpR, HpQ = sp.symbols("Hp_Rlin Hp_Q")
ETA_RLIN, ETA_Q, H_RLIN, H_Q = sp.symbols("eta_Rlin eta_Q H_Rlin H_Q")
BASE = ETA_RLIN + ETA_Q + H_RLIN + H_Q


def sym(prefix: str, power: int):
    return sp.Symbol(f"{prefix}{power}")


def case_0_statement(out: ScriptOutput) -> None:
    header("Case 0: Closure uniqueness program, tenth rung")
    print("Step 9 killed all split-density mismatch directions. This leaves")
    print("only equal-coefficient higher-H derivative terms:")
    print()
    print("  Hp.Rlin + Hp.Q")
    print()
    print("This rung checks that those terms are not new closures. They are")
    print("generated by choosing a nonlinear metric-density perturbation")
    print()
    print("  K = H + sum_p a_p Hp")
    print()
    print("inside the same Palatini replacement.")

    with out.governance_assessments():
        out.line(
            "higher-H field-redefinition reduction opened",
            StatusMark.INFO,
            "tests the remaining equal-coefficient tower",
        )


def case_1_generic_power_redefinition(out: ScriptOutput):
    header("Case 1: Generic equal-coefficient Hp term is a variable choice")
    palatini_h = BASE
    palatini_k = BASE + a * HpR + a * HpQ
    generated = sp.simplify(palatini_k - palatini_h)
    target = a * (HpR + HpQ)
    residual = sp.simplify(generated - target)

    print("For any fixed p >= 2:")
    print("  K = H + a_p Hp")
    print("Palatini replacement with K generates")
    print("  a_p Hp.Rlin + a_p Hp.Q")
    print(f"  residual vs a_p(Hp.Rlin + Hp.Q) = {sp.sstr(residual)}")

    ok = is_zero(residual)
    with out.derived_results():
        out.line(
            "generic equal-coefficient Hp direction is field-redefinition freedom",
            StatusMark.PASS if ok else StatusMark.FAIL,
            "K=H+a_pHp generates a_p Hp.(Rlin+Q)",
        )
    return ok


def case_2_finite_tower_redefinition(out: ScriptOutput):
    header("Case 2: Finite equal-coefficient tower is removable")
    hp_r = [sym("H", power * 10 + 1) for power in SAMPLE_POWERS]
    hp_q = [sym("H", power * 10 + 2) for power in SAMPLE_POWERS]
    a_symbols = [sym("a", power) for power in SAMPLE_POWERS]
    c_symbols = [sym("c", power) for power in SAMPLE_POWERS]

    generated = sum(a_i * (r_i + q_i) for a_i, r_i, q_i in zip(a_symbols, hp_r, hp_q))
    target = sum(c_i * (r_i + q_i) for c_i, r_i, q_i in zip(c_symbols, hp_r, hp_q))
    basis = hp_r + hp_q
    residual = sp.Poly(generated - target, *basis)
    equations = [sp.Eq(coeff, 0) for coeff in residual.coeffs()]
    solution = sp.solve(equations, a_symbols, dict=True)
    expected = [{a_i: c_i for a_i, c_i in zip(a_symbols, c_symbols)}]

    print(f"Sample equal-coefficient powers: {SAMPLE_POWERS}")
    print("Generated tower:")
    print("  sum_p a_p(Hp.Rlin + Hp.Q)")
    print("Target tower:")
    print("  sum_p c_p(Hp.Rlin + Hp.Q)")
    print(f"  redefinition solution = {solution}")

    ok = solution == expected
    with out.derived_results():
        out.line(
            "finite equal-coefficient higher-H tower is removable",
            StatusMark.PASS if ok else StatusMark.FAIL,
            "choosing a_p=c_p absorbs every equal-coefficient derivative term",
        )
    return ok


def case_3_deformation_space_status(out: ScriptOutput):
    header("Case 3: Derivative ansatz-reduction status")
    print("Combining the last rungs:")
    print()
    print("  H2 equal pair      -> field redefinition (step 6)")
    print("  H2 mismatch        -> connection-equation obstruction (step 8)")
    print("  Hp mismatch p>=3   -> connection-equation obstruction (step 9)")
    print("  Hp equal pair p>=3 -> field redefinition (this step)")
    print()
    print("Thus the higher-H two-derivative derivative tower is reduced:")
    print("mismatches are incompatible with connection elimination, and equal")
    print("directions are nonlinear metric-density variable choice.")
    print()
    print("What remains for final closure accounting is not a derivative")
    print("deformation: eta.Rlin is boundary, H.Rlin + eta.Q is the free core,")
    print("H.Q is the generated self-coupling, Lambda is admitted, and")
    print("higher-derivative/extra-field/torsion/nonuniversal couplings are")
    print("outside this theorem's scope.")

    with out.governance_assessments():
        out.line(
            "higher-H derivative ansatz reduction discharged",
            StatusMark.PASS,
            "all higher-H two-derivative directions are field redefinition or connection-inconsistent",
        )
    with out.unresolved_obligations():
        out.line(
            "closure uniqueness final accounting",
            StatusMark.OBLIGATION,
            "assemble the rung results into the final in-house closure theorem and retirement decision",
        )


def record_results(ns) -> None:
    ns.record_derivation(
        derivation_id="higher_h_field_redefinition_tower_018",
        inputs=[
            "h2_field_redefinition_locked_pair_018",
            "higher_h_mismatch_tower_excluded_018",
        ],
        output=sp.Symbol("K_eq_H_plus_sum_apHp_generates_sum_ap_Hp_Rlin_plus_Hp_Q"),
        method="coefficient matching of Palatini replacement under nonlinear metric-density variable choice",
        status=Status.DERIVED,
        record_kind=RecordKind.DERIVATION,
        result_type="closure_uniqueness_rung",
        scope="higher-H equal-coefficient derivative tower",
    )
    ns.record_derivation(
        derivation_id="higher_h_derivative_ansatz_reduction_018",
        inputs=[
            "higher_h_mismatch_tower_excluded_018",
            "higher_h_field_redefinition_tower_018",
        ],
        output=sp.Symbol("higher_H_derivative_tower_reduced_or_excluded"),
        method="mismatch exclusion plus equal-coefficient field-redefinition reduction",
        status=Status.DERIVED,
        record_kind=RecordKind.DERIVATION,
        result_type="closure_uniqueness_rung",
        scope="two-derivative first-order higher-H ansatz-reduction lemma",
    )
    ns.record_obligation(ProofObligationRecord(
        obligation_id="closure_uniqueness_inhouse_018",
        script_id=SCRIPT_ID,
        title="In-house self-coupled spin-2 closure uniqueness",
        status=ObligationStatus.OPEN,
        required_by=["field_equation_proof"],
        description=(
            "The higher-H two-derivative derivative tower has been reduced: "
            "mismatch directions are excluded by the connection-equation lock, "
            "and equal-coefficient directions are nonlinear metric-density "
            "field-redefinition freedom. Final closure accounting remains to "
            "assemble the theorem and decide whether the Deser citation can be retired."
        ),
    ))
    ns.record_claim(ClaimRecord(
        claim_id="closure_step_10_claim_018",
        script_id=SCRIPT_ID,
        claim_kind=RecordKind.GOVERNANCE_CLAIM,
        tier=ClaimTier.CONSTRAINED,
        status=GovernanceStatus.LICENSED_CLAIM,
        statement=(
            "After mismatch directions are excluded by the connection-equation "
            "operator lock, every surviving higher-H two-derivative derivative "
            "term has equal coefficients Hp.Rlin+Hp.Q. The nonlinear "
            "metric-density redefinition K=H+sum_p a_p Hp generates exactly "
            "sum_p a_p Hp.(Rlin+Q), so the equal-coefficient tower is variable "
            "choice rather than a new closure. The higher-H derivative ansatz "
            "reduction is therefore discharged; a final accounting rung remains "
            "before retiring the external citation."
        ),
        derivation_ids=[
            "higher_h_field_redefinition_tower_018",
            "higher_h_derivative_ansatz_reduction_018",
        ],
        obligation_ids=["closure_uniqueness_inhouse_018"],
    ))


def main() -> None:
    header("Trial 018: Closure Uniqueness Step 10")
    archive, ns, invalidated = prepare_archive()
    print_archive_status(ns, invalidated)

    out = ScriptOutput()
    case_0_statement(out)
    case_1_generic_power_redefinition(out)
    case_2_finite_tower_redefinition(out)
    case_3_deformation_space_status(out)

    record_results(ns)
    ns.write_run_metadata()


if __name__ == "__main__":
    main()
