# Trial 018: Closure uniqueness, step 5
#
# Script type:
#   RIGOR PROGRAM / ANSATZ-REDUCTION GATE
#
# Purpose
# -------
# This is the fifth in-house rung toward replacing the Deser 1970
# self-coupled spin-2 closure citation. It deliberately does not retire
# the full closure-uniqueness obligation.
#
# Steps 1-4 established:
#
#   1. conservation forces self-coupling;
#   2. the Palatini replacement gives a finite closure witness;
#   3. within that replacement ansatz, H.Q is the unique derivative
#      self-coupling and no H^2 tower is generated;
#   4. the Palatini endpoint eliminates the independent connection.
#
# This script turns the remaining "ansatz reduction" debt into a precise
# gate. It enumerates the local two-derivative first-order monomial
# classes in the Palatini variables and marks what is already discharged,
# admitted, forbidden by scope, or still open.
#
# Result: the Deser citation is narrowed to one missing lemma:
#
#   every admissible local, two-derivative, no-extra-field spin-2
#   completion must reduce to the Palatini replacement class up to
#   boundary terms, field redefinitions, normalization, and Lambda.

from pathlib import Path

import sympy as sp

from vacuumforge import ProjectArchive, Status
from vacuumforge.governance import (
    ClaimRecord,
    ClaimTier,
    GovernanceStatus,
    ObligationStatus,
    ProofObligationRecord,
    RecordKind,
    ScriptOutput,
    StatusMark,
)


ARCHIVE_ROOT = Path(__file__).resolve().parents[1] / ".vacuumforge_archive"
SCRIPT_ID = f"{Path(__file__).parent.name}__{Path(__file__).stem}"


def header(title: str) -> None:
    print()
    print("=" * 120)
    print(title)
    print("=" * 120)


def is_zero(expr) -> bool:
    try:
        return bool(sp.simplify(expr) == 0)
    except Exception:
        return False


def print_archive_status(ns, invalidated: bool) -> None:
    if invalidated:
        print("[INFO] Archive invalidated due to source change.")
    checks = ns.verify_dependencies()
    if not checks:
        print("[INFO] Archive dependencies: none declared.")
        return
    print("[INFO] Archive dependency check:")
    for check in checks:
        print(f"  - {check.dependency.dependency_id}: {check.status} ({check.message})")


def prepare_archive():
    archive = ProjectArchive(ARCHIVE_ROOT)
    ns = archive.script_namespace(SCRIPT_ID)
    invalidated = ns.check_source_invalidation(__file__)
    ns.declare_dependency(
        dependency_id="closure_step_4_dependency_018",
        upstream_script_id="018_closure_uniqueness__closure_step_4_connection_elimination",
        upstream_derivation_id="palatini_connection_uniqueness_018",
        expected_record_kind=RecordKind.DERIVATION,
    )
    return archive, ns, invalidated


H, R, Q, LAM = sp.symbols("H Rlin Q Lambda")


def monomial(h_power: int, operator: str):
    if operator == "Rlin":
        return H**h_power * R
    if operator == "Q":
        return H**h_power * Q
    if operator == "Lambda":
        return H**h_power * LAM
    raise ValueError(operator)


def degree(expr):
    powers = sp.Poly(expr, H, R, Q, LAM).monoms()[0]
    return {
        "H": powers[0],
        "Rlin": powers[1],
        "Q": powers[2],
        "Lambda": powers[3],
    }


DERIVATIVE_CLASSES = [
    {
        "name": "eta.Rlin",
        "expr": monomial(0, "Rlin"),
        "status": "boundary",
        "reason": "step 2: fixed-background eta.Rlin is a divergence",
    },
    {
        "name": "H.Rlin",
        "expr": monomial(1, "Rlin"),
        "status": "free_core",
        "reason": "linear spin-2 kinetic core",
    },
    {
        "name": "eta.Q",
        "expr": monomial(0, "Q"),
        "status": "free_core",
        "reason": "first-order free connection quadratic term",
    },
    {
        "name": "H.Q",
        "expr": monomial(1, "Q"),
        "status": "generated",
        "reason": "step 2/3: unique Palatini replacement self-coupling",
    },
    {
        "name": "H2.Rlin",
        "expr": monomial(2, "Rlin"),
        "status": "open_unless_reduced",
        "reason": "not generated by replacement; must be field-redefinition/boundary or excluded",
    },
    {
        "name": "H2.Q",
        "expr": monomial(2, "Q"),
        "status": "open_unless_reduced",
        "reason": "not generated by replacement; must be field-redefinition/boundary or excluded",
    },
]

NON_DERIVATIVE_CLASSES = [
    {
        "name": "Lambda density",
        "expr": monomial(0, "Lambda") + monomial(1, "Lambda") + monomial(2, "Lambda"),
        "status": "admitted_residual",
        "reason": "zero-derivative cosmological term remains permitted but not valued",
    }
]

SCOPE_EXCLUSIONS = [
    ("higher_derivative", "excluded by two-derivative closure scope and later ghost gate"),
    ("extra_field", "excluded by no-extra-field scope; routed fields belong outside this theorem"),
    ("torsion_nonmetricity", "excluded inside Palatini endpoint by step 4 connection elimination"),
    ("nonuniversal_matter_coupling", "excluded by K2 universal metric coupling"),
]


def case_0_statement(out: ScriptOutput) -> None:
    header("Case 0: Closure uniqueness program, fifth rung")
    print("This script does not prove the missing ansatz-reduction lemma.")
    print("It makes the remaining target exact by enumerating the local")
    print("two-derivative first-order classes already seen by the Palatini")
    print("witness and separating discharged, admitted, excluded, and open")
    print("directions.")

    with out.governance_assessments():
        out.line(
            "ansatz-reduction gate opened",
            StatusMark.INFO,
            "classification of remaining uniqueness debt; Deser citation still active",
        )


def case_1_derivative_classification(out: ScriptOutput):
    header("Case 1: Local two-derivative first-order derivative classes")
    statuses = {}
    for item in DERIVATIVE_CLASSES:
        deg = degree(item["expr"])
        statuses[item["name"]] = item["status"]
        print(f"  {item['name']:<10} degree={deg} status={item['status']}")
        print(f"    {item['reason']}")

    expected_open = {"H2.Rlin", "H2.Q"}
    actual_open = {name for name, status in statuses.items() if status == "open_unless_reduced"}
    discharged = {
        name
        for name, status in statuses.items()
        if status in {"boundary", "free_core", "generated"}
    }
    expected_discharged = {"eta.Rlin", "H.Rlin", "eta.Q", "H.Q"}

    ok = actual_open == expected_open and discharged == expected_discharged
    with out.derived_results():
        out.line(
            "derivative-class audit isolates only higher-H non-Palatini terms",
            StatusMark.PASS if ok else StatusMark.FAIL,
            "eta.Rlin/H.Rlin/eta.Q/H.Q are classified; H2.Rlin and H2.Q are the remaining ansatz-reduction targets",
        )
    return ok


def case_2_universal_replacement_vs_open_terms(out: ScriptOutput):
    header("Case 2: Universal replacement misses exactly the open derivative terms")
    replacement = monomial(0, "Rlin") + monomial(1, "Rlin") + monomial(0, "Q") + monomial(1, "Q")
    candidate_space = sum(item["expr"] for item in DERIVATIVE_CLASSES)
    open_terms = monomial(2, "Rlin") + monomial(2, "Q")
    residual = sp.simplify(candidate_space - replacement - open_terms)

    print("candidate derivative space through H^2:")
    print("  eta.Rlin + H.Rlin + eta.Q + H.Q + H2.Rlin + H2.Q")
    print("universal replacement derivative output:")
    print("  eta.Rlin + H.Rlin + eta.Q + H.Q")
    print(f"  residual after subtracting open terms = {sp.sstr(residual)}")

    ok = is_zero(residual)
    with out.derived_results():
        out.line(
            "universal replacement leaves only H2.Rlin and H2.Q as unresolved derivative classes",
            StatusMark.PASS if ok else StatusMark.FAIL,
            "the remaining proof must reduce or exclude those classes",
        )
    return ok


def case_3_scope_and_residuals(out: ScriptOutput):
    header("Case 3: Scope exclusions and admitted residual")
    for item in NON_DERIVATIVE_CLASSES:
        degs = [degree(term) for term in sp.Add.make_args(item["expr"])]
        print(f"  {item['name']}: status={item['status']} degree-samples={degs}")
        print(f"    {item['reason']}")

    for name, reason in SCOPE_EXCLUSIONS:
        print(f"  {name}: excluded")
        print(f"    {reason}")

    status_counts = {
        "admitted": len(NON_DERIVATIVE_CLASSES),
        "excluded": len(SCOPE_EXCLUSIONS),
    }
    ok = status_counts == {"admitted": 1, "excluded": 4}
    with out.governance_assessments():
        out.line(
            "non-derivative residual and scope exclusions recorded",
            StatusMark.PASS if ok else StatusMark.FAIL,
            "Lambda admitted; higher derivatives, extra fields, torsion/nonmetricity, and nonuniversal coupling are outside this closure theorem",
        )
    return ok


def case_4_precise_remaining_lemma(out: ScriptOutput):
    header("Case 4: Precise remaining lemma")
    print("The missing theorem is now:")
    print()
    print("  Under locality, two-derivative order, no extra fields, torsion-free")
    print("  Palatini variables, relabeling gauge consistency, and universal")
    print("  self-coupling, every admissible H^p.Rlin or H^p.Q deformation with")
    print("  p >= 2 is either:")
    print()
    print("    1. a boundary term,")
    print("    2. removable by field redefinition,")
    print("    3. a normalization change already fixed elsewhere, or")
    print("    4. inconsistent with the gauge/conservation identities.")
    print()
    print("Once that lemma is proved, the in-house proof can retire the Deser")
    print("citation. Until then, the citation remains active.")

    with out.unresolved_obligations():
        out.line(
            "ansatz-reduction lemma for higher-H two-derivative deformations",
            StatusMark.OBLIGATION,
            "reduce/exclude H^p.Rlin and H^p.Q for p >= 2 under the closure assumptions",
        )


def record_results(ns) -> None:
    ns.record_derivation(
        derivation_id="palatini_ansatz_reduction_gate_018",
        inputs=[
            "palatini_replacement_coefficient_audit_018",
            "palatini_connection_uniqueness_018",
        ],
        output=sp.Symbol("remaining_gap_is_higher_H_derivative_ansatz_reduction"),
        method="classification of first-order two-derivative monomial classes by H degree and status",
        status=Status.DERIVED,
        record_kind=RecordKind.DERIVATION,
        result_type="closure_uniqueness_rung",
        scope="ansatz-reduction gate; not full closure uniqueness",
    )
    ns.record_obligation(ProofObligationRecord(
        obligation_id="closure_uniqueness_inhouse_018",
        script_id=SCRIPT_ID,
        title="In-house self-coupled spin-2 closure uniqueness",
        status=ObligationStatus.OPEN,
        required_by=["field_equation_proof"],
        description=(
            "The remaining Deser-replacement debt is narrowed to the "
            "ansatz-reduction lemma for higher-H two-derivative deformations: "
            "reduce or exclude H^p.Rlin and H^p.Q for p >= 2 under locality, "
            "gauge consistency, universal coupling, and no-extra-field assumptions."
        ),
    ))
    ns.record_claim(ClaimRecord(
        claim_id="closure_step_5_claim_018",
        script_id=SCRIPT_ID,
        claim_kind=RecordKind.GOVERNANCE_CLAIM,
        tier=ClaimTier.CONSTRAINED,
        status=GovernanceStatus.LICENSED_CLAIM,
        statement=(
            "After the first four closure rungs, the remaining in-house "
            "Deser-replacement problem is isolated to the ansatz-reduction "
            "lemma. The Palatini replacement accounts for eta.Rlin, H.Rlin, "
            "eta.Q, and H.Q; Lambda is admitted separately; higher derivatives, "
            "extra fields, torsion/nonmetricity, and nonuniversal matter "
            "couplings are outside the theorem's scope. What remains is to "
            "reduce or exclude higher-H two-derivative deformations."
        ),
        derivation_ids=["palatini_ansatz_reduction_gate_018"],
        obligation_ids=["closure_uniqueness_inhouse_018"],
    ))


def main() -> None:
    header("Trial 018: Closure Uniqueness Step 5")
    archive, ns, invalidated = prepare_archive()
    print_archive_status(ns, invalidated)

    out = ScriptOutput()
    case_0_statement(out)
    case_1_derivative_classification(out)
    case_2_universal_replacement_vs_open_terms(out)
    case_3_scope_and_residuals(out)
    case_4_precise_remaining_lemma(out)

    record_results(ns)
    ns.write_run_metadata()


if __name__ == "__main__":
    main()
