#!/usr/bin/env python3
"""
make_9_galerkin_variational_matrix_test.py

Compare the projection matrix A against the stiffness matrix generated by the
candidate variational operator L*_w L.

Output:
    9_galerkin_variational_matrix_test.md
"""

from pathlib import Path
import sympy as sp


x = sp.symbols("x", real=True)
a = 1 - x**2
w = a**4


def simplify_expr(expr):
    out = sp.simplify(expr)
    out = sp.factor(out)
    out = sp.cancel(out)
    out = sp.factor(out)
    return out


def require_zero(label, expr):
    result = simplify_expr(expr)
    if result != 0:
        raise AssertionError(f"{label} failed:\n{result}")


def require_equal(label, lhs, rhs):
    require_zero(label, lhs - rhs)


def L(expr):
    return sp.expand(a * sp.diff(expr, x) - 6 * x * expr)


def Lstar(expr):
    return sp.expand(-a * sp.diff(expr, x) + 4 * x * expr)


def integrate_poly(expr):
    return sp.integrate(sp.expand(expr), (x, 0, 1))


def phi(j):
    return x ** (2 * j)


def psi(k):
    r = sp.Rational(2 * k - 1, 2 * k + 3)
    return x ** (2 * k) - r * x ** (2 * k - 2)


checks = []
N = 5

A = sp.Matrix(
    [
        [2 * integrate_poly(psi(k) * phi(j) * w) for j in range(N)]
        for k in range(1, N + 1)
    ]
)

K = sp.Matrix(
    [
        [integrate_poly(L(phi(i)) * L(phi(j)) * w) for j in range(N)]
        for i in range(N)
    ]
)

P = sp.Matrix(
    [
        [integrate_poly(phi(i) * Lstar(L(phi(j))) * w) for j in range(N)]
        for i in range(N)
    ]
)

# Variational stiffness identity:
#
#   <phi_i, L*_w L phi_j>_w = <L phi_i, L phi_j>_w
#
# for the even monomial basis; boundary terms vanish.
for i in range(N):
    for j in range(N):
        require_equal(f"stiffness identity i={i} j={j}", P[i, j], K[i, j])
checks.append("Galerkin stiffness identity on even monomial grid")

# The original projection matrix is not the same object as the stiffness
# matrix.  A single exact counterexample is enough.
counter_A = A[0, 0]
counter_K = K[0, 0]
if simplify_expr(counter_A - counter_K) == 0:
    raise AssertionError("A[1,0] unexpectedly equals K[0,0]")
checks.append("projection matrix is not identical to stiffness matrix")

# Psi-tested parent matrix:
#
#   Q[k,j] = <psi_k, L*_w L phi_j>_w
#
# This is a higher-order tested parent-equation matrix, distinct from A and K.
Q = sp.Matrix(
    [
        [integrate_poly(psi(k) * Lstar(L(phi(j))) * w) for j in range(N)]
        for k in range(1, N + 1)
    ]
)

if Q.shape != A.shape:
    raise AssertionError("Q and A should have matching shape")
if simplify_expr(Q[0, 0] - A[0, 0]) == 0:
    raise AssertionError("Q[1,0] unexpectedly equals A[1,0]")
checks.append("psi-tested parent matrix is distinct from A")

validation_bullets = "\n".join("- " + item + ": passed" for item in checks)

md = f"""# Synthesis Proof 9: Galerkin and Variational Matrix Test

## Purpose

This report compares three exact matrices:

```text
A[k,j] = 2 <psi_k, phi_j>_w
K[i,j] = <L phi_i, L phi_j>_w
P[i,j] = <phi_i, L*_w L phi_j>_w
```

The goal is to clarify whether the existing projection matrix is directly the
variational stiffness matrix.

## Validated Identities

{validation_bullets}

## Result

The variational stiffness matrix is:

```text
K[i,j] = <L phi_i, L phi_j>_w.
```

SymPy verifies on the exact even-monomial grid that:

```text
<phi_i, L*_w L phi_j>_w = <L phi_i, L phi_j>_w.
```

The original projection matrix:

```text
A[k,j] = 2 <psi_k, phi_j>_w
```

is not the same matrix as `K`. For example:

```text
A[1,0] = {counter_A}
K[0,0] = {counter_K}
```

Thus `A` is not directly the stiffness matrix of the candidate variational
problem. It is the once-integrated projection/pullback matrix associated with
the row tests `psi_k`.

## Exact Matrices

`A`, rows `k=1..{N}`, columns `j=0..{N - 1}`:

```text
{A}
```

`K`, rows/columns `i,j=0..{N - 1}`:

```text
{K}
```

`Q[k,j] = <psi_k, L*_w L phi_j>_w`, rows `k=1..{N}`, columns `j=0..{N - 1}`:

```text
{Q}
```
"""

out = Path(__file__).with_name("9_galerkin_variational_matrix_test.md")
tmp = out.with_suffix(out.suffix + ".tmp")
tmp.write_text(md, encoding="utf-8")
tmp.replace(out)

print("All symbolic checks passed.")
print(f"Wrote {out.resolve()}")


